// Every root field name here was read out of src/data/schema.json, which is
// generated by `npm run introspect`. Ponder pluralises by appending "s" to the
// table name, which is why the canvas list field is `canvass` — do not "fix" it.

import { gql, type GqlOptions } from "./client.ts";
import type { StrokeRecord } from "../core/decode.ts";

export const PAGE_LIMIT = 1000;

const DAY_STROKES = `
query DayStrokes($canvasId: Int!, $after: String, $limit: Int!) {
  strokes(
    where: { canvasId: $canvasId }
    orderBy: "id"
    orderDirection: "asc"
    limit: $limit
    after: $after
  ) {
    items { id accountId data pixels timestamp }
    pageInfo { hasNextPage endCursor }
    totalCount
  }
}`;

const DAY_STROKES_AFTER_ID = `
query DayStrokesAfterId($canvasId: Int!, $afterId: BigInt!, $after: String, $limit: Int!) {
  strokes(
    where: { canvasId: $canvasId, id_gt: $afterId }
    orderBy: "id"
    orderDirection: "asc"
    limit: $limit
    after: $after
  ) {
    items { id accountId data pixels timestamp }
    pageInfo { hasNextPage endCursor }
    totalCount
  }
}`;

const DAY_CANVAS = `
query DayCanvas($id: Int!) {
  canvas(id: $id) {
    id name size palette proposer
    totalArtists pixelsCount totalMints totalBurns totalEarned
  }
}`;

const ARTIST_DAYS = `
query ArtistDays($accountId: String!, $limit: Int!) {
  contributions(
    where: { accountId: $accountId }
    orderBy: "canvasId"
    orderDirection: "desc"
    limit: $limit
  ) {
    items { canvasId pixelsCount }
    totalCount
  }
}`;

const ARTIST_ACCOUNT = `
query ArtistAccount($id: String!) {
  account(id: $id) {
    id totalPixels totalDaysPainted lastPaintedDay streak longestStreak
  }
}`;

interface StrokePage {
  strokes: {
    items: StrokeRecord[];
    pageInfo: { hasNextPage: boolean; endCursor: string | null };
    totalCount: number;
  };
}

export interface CanvasRecord {
  id: number;
  name: string | null;
  size: number | null;
  palette: string | null;
  proposer: string | null;
  totalArtists: number;
  pixelsCount: number;
  totalMints: number;
  totalBurns: number;
  totalEarned: string;
}

export interface ArtistDay {
  canvasId: number;
  pixelsCount: number;
}

export interface AccountRecord {
  id: string;
  totalPixels: number;
  totalDaysPainted: number;
  lastPaintedDay: number | null;
  streak: number;
  longestStreak: number;
}

export interface StrokePageResult {
  items: StrokeRecord[];
  hasNextPage: boolean;
  endCursor: string | null;
  totalCount: number;
}

/** One page of a day's strokes, in id order. `afterId` skips ids already held. */
export async function fetchStrokePage(
  canvasId: number,
  cursor: string | null,
  afterId: bigint | null,
  options: GqlOptions = {},
): Promise<StrokePageResult> {
  const data = await gql<StrokePage>(
    afterId === null ? DAY_STROKES : DAY_STROKES_AFTER_ID,
    afterId === null
      ? { canvasId, after: cursor, limit: PAGE_LIMIT }
      : { canvasId, afterId: afterId.toString(), after: cursor, limit: PAGE_LIMIT },
    options,
  );
  const page = data.strokes;
  return {
    items: page.items,
    hasNextPage: page.pageInfo.hasNextPage,
    endCursor: page.pageInfo.endCursor,
    totalCount: page.totalCount,
  };
}

export interface StrokeProgress {
  strokes: number;
  pixels: number;
  totalStrokes: number;
  page: number;
}

/**
 * Pages a whole day. `id` is a bigint string and is the chronological order the
 * canvas itself was built in — never re-sort by timestamp, several strokes share
 * one.
 */
export async function fetchDayStrokes(
  canvasId: number,
  onPage: (items: StrokeRecord[], progress: StrokeProgress) => void,
  options: GqlOptions & { afterId?: bigint | null } = {},
): Promise<{ pages: number; lastId: bigint | null }> {
  const { afterId = null, ...gqlOptions } = options;
  let cursor: string | null = null;
  let pages = 0;
  let strokes = 0;
  let pixels = 0;
  let lastId: bigint | null = null;

  for (;;) {
    const page: StrokePageResult = await fetchStrokePage(canvasId, cursor, afterId, gqlOptions);
    pages++;
    strokes += page.items.length;
    for (const s of page.items) pixels += s.pixels;
    const last = page.items[page.items.length - 1];
    if (last) lastId = BigInt(last.id);
    onPage(page.items, { strokes, pixels, totalStrokes: page.totalCount, page: pages });
    if (!page.hasNextPage || page.items.length === 0) break;
    cursor = page.endCursor;
    if (cursor === null) break;
  }

  return { pages, lastId };
}

export async function fetchCanvas(
  id: number,
  options: GqlOptions = {},
): Promise<CanvasRecord | null> {
  const data = await gql<{ canvas: CanvasRecord | null }>(DAY_CANVAS, { id }, options);
  return data.canvas;
}

export async function fetchArtistDays(
  address: string,
  limit: number,
  options: GqlOptions = {},
): Promise<{ days: ArtistDay[]; totalDays: number }> {
  const data = await gql<{ contributions: { items: ArtistDay[]; totalCount: number } }>(
    ARTIST_DAYS,
    { accountId: address, limit },
    options,
  );
  return { days: data.contributions.items, totalDays: data.contributions.totalCount };
}

export async function fetchAccount(
  address: string,
  options: GqlOptions = {},
): Promise<AccountRecord | null> {
  const data = await gql<{ account: AccountRecord | null }>(ARTIST_ACCOUNT, { id: address }, options);
  return data.account;
}
